[package]
name = "wluma"
version = "4.0.0"
authors = ["Maxim Baz"]
edition = "2018"

[dependencies]
wayland-client = "0.29.0"
wayland-protocols = { version = "0.29.0", features = ["client", "unstable_protocols"] }
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
dirs = "3.0"
toml = { git = "https://github.com/vgao1996/toml-rs", branch = "dotted-table-0.5.8" }
chrono = "0.4"
ash = "0.35"
itertools = "0.10"
v4l = { version = "0.12", features = ["libv4l"], default-features = false }
ddc-hi = "0.4"
log = "0.4"
env_logger = "0.9"
inotify = "0.10"

[dev-dependencies]
mockall = "0.10"
