[frame]
processor = "vulkan"
capturer = "wlroots"
# capturer = "none" # Does not capture screen contents, just uses ALS to predict ideal screen brightness

[als.iio]
path = "/sys/bus/iio/devices"
thresholds = [ 20, 80, 250, 500, 800 ]

# [als.webcam]
# video = 0
# thresholds = [ 15, 30, 45, 60, 75 ]

# [als.time]
# hour_to_lux = { 7 = 1, 9 = 2, 11 = 3, 13 = 4, 16 = 3, 18 = 1, 20 = 0 }

# [als.none]

# TODO multi-monitor setup is not supported, but wanted!
[[output.backlight]]
name = "Unknown (0x633D)"
path = "/sys/class/backlight/intel_backlight"

###################################################################
# to get DP-1 and ABCDEFG you can use `swaymsg -t get_outputs` in
# running sway.
# #################################################################
#
# [[output.ddcutil]]
# name = "Dell Inc. (DELL P2415Q)"
# serial_number = "ABCDEFG"
#
# TODO everything below is an idea, not supported but definitely wanted!
# [keyboard.backlight.dell]
# path = "/sys/bus/platform/devices/dell-laptop/leds/dell::kbd_backlight"
#
# [keyboard.backlight.thinkpad]
# path = "/sys/bus/platform/devices/thinkpad_acpi/leds/tpacpi::kbd_backlight"
