name: Feature request
description: File a feature request
title: "[Feature request]: "
body:
  - type: markdown
    attributes:
      value: |
        ### Thanks for your time and effort in making the project better!
  - type: textarea
    id: description
    attributes:
      label: Please describe your feature request
    validations:
      required: true
