name: Feature request
description: File a feature request
title: "[Feature request]: "
labels: ["feature", "triage"]
assignees:
  - cyrinux
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to describe your needs
  - type: textarea
    id: what-needed
    attributes:
      label: Describe your request
      placeholder: Tell us what you need
      value: "Please write here the feature you miss"
    validations:
      required: true
